### ISSUE TITLE
درگاه پرداختی یا وجود ندارد یا آماده سرویس دهی نمی باشد

### ISSUE THREAD

**Issue by mokhosh** [iamtartan/laravel-online-payment#17]
طبق داکیومنتیشن پیش رفتم اما با این خطا روبرو میشم
تو محیط توسعه هستم
تست بانک هم متوجه نشدم چجوری استفاده میشه توی داکیومنتیشن نیست و سایت خود تست بانک ۴۰۴ میده

**Comment by iamtartan** [comment]
شما برای استفاده از «بانک تست» باید اکانتشو تهیه کنید. برای اینکه بدونید چطوریه کافیه سایتش رو ببینید
[banktest.ir](http://banktest.ir)

**Comment by mokhosh** [comment]
متاسفانه یو ایکس خوبی نداره این سایت
من اول ثبت نام نمیکنم بعد ببینم به دردم میخوره یا نه
اول باید قانع بشم که سرویس به درد بخوری هست
با توجه به این که این صفحه ۴۰۴ میده طبیعتا حس خوبی بهش ندارم
http://banktest.ir/%D8%AF%D8%B1%DA%AF%D8%A7%D9%87-%D9%BE%D8%B1%D8%AF%D8%A7%D8%AE%D8%AA-%D8%B2%D8%B1%DB%8C%D9%86-%D9%BE%D9%84/
