### ISSUE TITLE
Error: Declaration of Tartan\Larapay\Models\LarapayTransaction::setReferenceId

### ISSUE THREAD

**Issue by amin98362** [iamtartan/laravel-online-payment#20]
Hi
in:
tartan/laravel-online-payment": "^7.0
laravel/framework": "5.8.*

I get this error:
Declaration of Tartan\Larapay\Models\LarapayTransaction::setReferenceId($referenceId, $save = true): bool must be compatible with Tartan\Larapay\Transaction\TransactionInterface::setReferenceId(string $referenceId, bool $save = true): bool

**Comment by iamtartan** [comment]
There is no method `setReferenceId` in `Tartan\Larapay\Models\LarapayTransaction` class!  Where is this method in your reported issue comes from!!!
See: [LarapayTransaction.php](https://github.com/iamtartan/laravel-online-payment/blob/v7.0.5/src/Models/LarapayTransaction.php)

**Comment by amin98362** [comment]
There is "setReferenceId" method in TransactionInterface that LarapayTransaction implements TransactionInterface.
I replaced "LarapayTransaction.php" you mentioned with "LarapayTransaction.php" that I have in "tartan/laravel-online-payment": "^7.0" but still I get error.
When I call index method in BankController I get this error:

<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Tartan\Larapay\Models\Enum\Bank;
use App\User;

class BankController extends Controller
{
    public function index()
    {
        //your logic and prepare your order
        // ...
    	$user = User::find(142);
        //if you implement getAmount() method you can set amount to null
        $amount = 1200000;  //Rial at least 1000 
        //order or user description
        $description = 'I pay my order with Larapay <3';
        //some additional data that you need store on transaction
        $additionalData = [];
        //create transaction 
        $transaction = $user->createTransaction(Bank::MELLAT, $amount, $description, $additionalData);
        
        //auto submit bank form and transfer user to gateway
        $autoSubmit = true;
        //callback route name. if you set it on your .env file you can set this to null
        $callbackRouteName = 'payment.callback';
        //adapter config
        $adapterConfig = [];
        //generate bank form
        $form = $transaction->generateForm($autoSubmit, $callbackRouteName, $adapterConfig);
        
        return view('go-to-bank',[
            'form' => $form,
        ]);
    }
}

I Use Payable trait in User model.

**Comment by iamtartan** [comment]
Fixed at new release v7.0.7, Please check again.
