### ISSUE TITLE
Public Key file does not exist in specified path.

### ISSUE THREAD

**Issue by SSEsmaeeli** [iamtartan/laravel-online-payment#25]
Hello, for implemeting Saderat Bank gateway, I saw in config file that it needs a public and private key file.
Saderat Bank did not give us these two ... so how should it be generated?

**Comment by iamtartan** [comment]
Unfortunately, The Saderat gateway has changed its implementation completely so the Saderat adapter of Larapay component needs a lot of changes and it does not work until then.

**Comment by SSEsmaeeli** [comment]
Ok, Thanks for your answer, 
yes after searching a bit, I found out that they switched to version 2.
