### ISSUE TITLE
نمونه کد

### ISSUE THREAD

**Issue by p30web** [iamtartan/laravel-online-payment#4]
سلام 

کاش داکیومنت های این پروژه رو کامل کنید 

و یک آموزش کامل تر و یا یک نمونه کد و یا یک نمونه پروژه از آن را قرار بدهید 

این گونه توسعه دهنده هایی که تازه میخواهند با این پکیج کار کنند ، فکر میکنم کارشون راحت تر باشه

**Comment by iamtartan** [comment]
داکیومنت کامل شد
