### ISSUE TITLE
TransactionInterface

### ISSUE THREAD

**Issue by nabidam** [iamtartan/laravel-online-payment#9]
سلام، بنده به خطایی در رابطه با 
`TransactionInterface`
 برخوردم.

> Class App\Transaction contains 15 abstract methods and must therefore be declared abstract or implement the remaining methods (Tartan\Larapay\Transaction\TransactionInterface::setGatewayToken, Tartan\Larapay\Transaction\TransactionInterface::setReferenceId, Tartan\Larapay\Transaction\TransactionInterface::checkForRequestToken, ...)

ممنون میشم راهنماییم کنید.

**Comment by iamtartan** [comment]
سلام
خطا که کاملا مشخصه و خودش همه چیز رو گفته! کلاس 
App\Transaction 
شما کلاس 
Tartan\Larapay\Transaction\TransactionInterface
رو ایمپلیمنت کرده در نتیجه باید تمام متدهای اون رو پیاده سازی بکنه و ظاهرا کلاس شما همه متدهارو پیاده سازی نکرده و همش یا چند تاییش که اشاره شده باقی مونده. 
خطای شما مربوط به لاراپی یا هر کامپوننت دیگه ای نیست اصلا مربوط به استاندارد برنامه نویسی شی گراست. شما تو زبون پی اچ پی یا هر زبون دیگه ای کلاستون هر کلاس اینترفیس دیگه ای رو ایمپلیمنت بکنه قاعدتا باید تمام متدهای اون کلاس رو پیاده سازی بکنه این جزو اصول برنامه نویسیه و کاملا واضحه. امیدوارم جواب سوالتون رو گرفته باشید.
